#!/usr/bin/env bash

write_config(){
  truncate -s 0 ~/.coff_config
  {
    echo "PATH TO QUESTION"
    echo "$HOME/coff/quest"
    echo "PATH TO ANSWER"
    echo "$HOME/coff/ans"
  } >> ~/.coff_config
}

if [ -e ~/.coff_config ]
then
  echo ""
  echo -n "Re-write config file \"~/.coff_config\" with default values? [y/n]: "

  while :
  do
    read -r CHOICE
    if [[ "$CHOICE" = "y" || "$CHOICE" = "Y" ]]
    then
      write_config
      break

    elif [[ "$CHOICE" = "n" || "$CHOICE" = "N" ]]
    then
      break

    else
      echo -n "Enter [y/n]: "
      continue
    fi

  done

else
  write_config
fi

mkdir -p ~/coff/quest ~/coff/ans ~/coff/null
cp ./samples/* ~/coff/quest
echo ""
